# Generated by Django 6.0.6 on 2026-06-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aula",
            name="codigo_qr_token",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True, unique=True
            ),
        ),
    ]
