# Generated by Django 6.0.6 on 2026-07-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0002_alter_aula_codigo_qr_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aula",
            name="capacidad_examen",
        ),
        migrations.AlterField(
            model_name="aula",
            name="numero_aula",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="incidencia",
            name="gravedad",
            field=models.CharField(
                choices=[("baja", "Baja"), ("media", "Media"), ("alta", "Alta")],
                default="baja",
                max_length=20,
            ),
        ),
    ]
