# Generated by Django 6.0.6 on 2026-07-13 14:40

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservas",
            "0003_remove_aula_capacidad_examen_alter_aula_numero_aula_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aula",
            options={
                "ordering": [
                    "edificio",
                    "planta",
                    django.db.models.functions.comparison.Cast(
                        "numero_aula", output_field=models.IntegerField()
                    ),
                ]
            },
        ),
        migrations.AlterField(
            model_name="aula",
            name="numero_aula",
            field=models.CharField(max_length=10),
        ),
    ]
