# Generated by Django 6.0.6 on 2026-07-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0004_alter_aula_options_alter_aula_numero_aula"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aula",
            options={},
        ),
    ]
