# Generated by Django 6.0.6 on 2026-07-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0005_alter_aula_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="correo_personal",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="despacho",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="foto_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="perfiles/"),
        ),
    ]
