# Generated by Django 6.0.6 on 2026-07-18 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0006_usuario_correo_personal_usuario_despacho_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SugerenciaAula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntuacion", models.PositiveIntegerField(default=5)),
                ("comentario", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sugerencias",
                        to="reservas.aula",
                    ),
                ),
                (
                    "reserva",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoracion",
                        to="reservas.reserva",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
