# Generated by Django 6.0.6 on 2026-07-23 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0007_sugerenciaaula"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SugerenciaAula",
            new_name="Valoracion",
        ),
        migrations.RemoveField(
            model_name="incidencia",
            name="recurso",
        ),
    ]
